version: "3.8"

services:
  lifelink:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=False
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
